server {
    listen 80;
    server_name otavianozibetti.tech www.otavianozibetti.tech;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name otavianozibetti.tech www.otavianozibetti.tech;

    ssl_certificate     /etc/letsencrypt/live/otavianozibetti.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/otavianozibetti.tech/privkey.pem;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    root  /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
